# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
  # Set the formatter 
  formatter: stylish
# File Options
files:
  include: '**/*.s+(a|c)ss'
# Rule Configuration
rules:
  indentation:
    - 0
    -
      size: 2
  empty-line-between-blocks: 0
  no-important: 0
  class-name-format: 2
  no-css-comments: 0
  single-line-per-selector: 0
  no-url-domains: 0
  no-url-protocols: 0
  hex-length: 0
  property-sort-order: 0
  force-element-nesting: 0